{
 "title": "Kuberhealthy",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Kuberhealthy Running",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "avg(kuberhealthy_running)" }
   ]
  },
  {
   "title": "Kuberhealthy Deployment check seconds",
   "type": "graph",
   "gridPos": { "h": 18, "w": 18, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kuberhealthy_check_duration_seconds{check=\"kuberhealthy/deployment\"})",
     "legendFormat": "deployment seconds"
    }
   ]
  },
  {
   "title": "Cluster Health",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(kuberhealthy_cluster_state)"
    }
   ]
  },
  {
   "title": "Kuberhealthy Check Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "avg(kuberhealthy_check) by(check)"
    }
   ]
  },
  {
   "title": "30d Moving Synthetic Deployment Uptime",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (sum(count_over_time(kuberhealthy_check{check=\"kuberhealthy/deployment\", status=\"0\"}[30d])) OR vector(0))/(sum(count_over_time(kuberhealthy_check{check=\"kuberhealthy/deployment\", status=\"1\"}[30d])) * 100)"
    }
   ]
  }
 ]
}