    spec:
      containers:
      - args:
        - /bin/sh
        - -c
        - sleep 5 && tail -n+1 -f /tmp/datelog.txt
        image: docker.io/busybox:latest
        imagePullPolicy: Always
        name: logging-sidecar
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      - image: quay.io/gpte-devops-automation/logtofile@sha256:bf1dfd99bfc4840132068c8b4551482792554f84d8b178a4fa1a72b1f31c7d4c
        imagePullPolicy: Always
        name: logging
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      volumes:
      - emptyDir: {}
        name: tmp