apiVersion: v1
kind: Service
metadata:
  labels:
    app: nexus
  name: nexus-registry
  namespace: c0e7-nexus
spec:
  ports:
  - name: 5000-tcp
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: nexus
    deploymentconfig: nexus
